#!/bin/bash
# post-merge hook only runs when an actual merge commit happens in your local repo, so it runs on git pull when there is a change in the code 

echo "🧹 Limpando branches locais já mescladas... NO POST-MERGE"

# Atualiza referências remotas e remove as deletadas
git fetch --prune
git branch --merged dev | grep -Ev '^\s*(\*?\s*)?(dev|main|master)$' | xargs -r -n 1 git branch -d

